# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish
on:
  push:
    branches: [ mhijazi1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get install gcc-avr
        python -m pip install --upgrade pip
        pip install --user qmk
        qmk setup -y
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Build
      run: |
        qmk compile -kb ergodox_ez/glow -km mhijazi1
        cp .build/ergodox_ez_glow_mhijazi1.hex .build/${{ steps.date.outputs.date }}.hex
    - name: Upload build artifact
      uses: actions/upload-artifact@v2.2.4
      with: 
        path: .build/${{ steps.date.outputs.date }}.hex
